version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
  vm-install-tools: entur/vm-install-tools@0.0.6

jobs:
  test:
    machine: true
    working_directory: ~/app
    steps:
      - checkout

      - vm-install-tools/install-java11

      - run: mvn test

      - run: mvn package

  deploy:
    machine: true
    working_directory: ~/app
    steps:
      - checkout

      - vm-install-tools/install-java11

      - run: mvn clean

      - run: mvn test

      - run: mvn jacoco:report

      - codecov/upload:
          file: ./target/site/jacoco/jacoco.xml

      - run: mvn package

      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install --upgrade setuptools==34.0.1
            sudo pip install awsebcli --upgrade

      - run:
          name: Deploying
          command: eb deploy RetropolisBe-env-1 --debug


workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only:
                - master