version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  test:
    working_directory: ~/app
    machine: true
    steps:
      - checkout

      - run: mvn test

      - run: mvn package

  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/openjdk:11-stretch-node
    steps:
      - checkout

      - run: mvn clean

      - run: mvn test

      - run: mvn jacoco:report

      - codecov/upload:
          file: ./target/site/jacoco/jacoco.xml

      - run: mvn package

      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install --upgrade setuptools
            sudo pip install awsebcli --upgrade

      - run:
          name: Deploying
          command: eb deploy RetropolisBe-env-1 --debug


workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only:
                - master